Edited "BreakableBlockManager" script to fix bug
I couldn't run the game, it was throwing this error:
 ArgumentException: An item with the same key has already been added. Key: Breakable Block (UnityEngine.GameObject)
 System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <1eb9db207454431c84a47bcd81e79c37>:0)
 System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <1eb9db207454431c84a47bcd81e79c37>:0)
 BreakableBlockManager.OnValidate () (at Assets/Scripts/BreakableBlockManager.cs:25)